document.addEventListener("DOMContentLoaded", () => {
    const body = document.body;
    const toggleButton = document.getElementById('theme-toggle');
    const tips = [
"Decision 1 Tip: In the simplex method, choose the most negative value in the objective row for a maximisation problem.",
"Decision 1 Fun Fact: Every linear programming optimum occurs at a vertex of the feasible region.",
"Decision 1 Tip: Always check feasibility before applying the simplex algorithm.",
"Decision 1 Fun Fact: Dijkstra’s algorithm does not work with negative edge weights.",
"Decision 1 Tip: In the Big M method, artificial variables must be removed from the basis by the final solution.",
"Decision 1 Fun Fact: A minimum spanning tree of n vertices always has n minus 1 edges.",
"Decision 1 Tip: When performing the ratio test, ignore negative or zero pivot column entries.",
"Decision 1 Fun Fact: The Hungarian algorithm guarantees an optimal assignment solution.",
"Decision 1 Tip: Critical activities in a project network have zero total float.",
"Decision 1 Fun Fact: The simplex method can visit multiple vertices before reaching optimality.",
"Further Mechanics 1 Tip: Always resolve forces parallel and perpendicular to the plane.",
"Further Mechanics 1 Fun Fact: The acceleration in uniform circular motion changes direction but not magnitude.",
"Further Mechanics 1 Tip: Use SUVAT equations only when acceleration is constant.",
"Further Mechanics 1 Fun Fact: Impulse is equal to the area under a force time graph.",
"Further Mechanics 1 Tip: Draw a clear free body diagram before forming equations.",
"Further Mechanics 1 Fun Fact: A projectile’s horizontal and vertical motions are independent.",
"Further Mechanics 1 Tip: Check whether a string is light and inextensible before assuming equal tension.",
"Further Mechanics 1 Fun Fact: The maximum height of a projectile depends only on vertical velocity.",
"Core Pure 1 Tip: Remember that i squared equals negative one.",
"Core Pure 1 Fun Fact: Complex numbers can be represented as points on an Argand diagram.",
"Core Pure 1 Tip: A matrix has an inverse only if its determinant is non zero.",
"Core Pure 1 Fun Fact: Matrix multiplication is not commutative.",
"Core Pure 1 Tip: In proof by induction, clearly state the base case.",
"Core Pure 1 Fun Fact: The binomial expansion coefficients form Pascal’s triangle.",
"Core Pure 1 Tip: When solving complex equations, equate real and imaginary parts separately.",
"Core Pure 1 Fun Fact: The modulus of a complex number is always non negative.",
"Core Pure 2 Tip: The derivative of e to the power x is itself.",
"Core Pure 2 Fun Fact: ln of a product equals the sum of the logs.",
"Core Pure 2 Tip: If two vectors are perpendicular, their dot product equals zero.",
"Core Pure 2 Fun Fact: Hyperbolic cosine squared minus hyperbolic sine squared equals one.",
"Core Pure 2 Tip: Use integration by parts when you see a product of functions.",
"Core Pure 2 Fun Fact: The Maclaurin series is just a Taylor series centred at zero.",
"Core Pure 2 Tip: When using substitution in integration, change the limits if definite.",
"Core Pure 2 Fun Fact: The scalar product measures how aligned two vectors are.",
"Maths Tip: Use completing the square to find the turning point of a quadratic.",
"Maths Fun Fact: The discriminant tells you how many real roots a quadratic has.",
"Maths Tip: Always check units in mechanics questions.",
"Maths Fun Fact: The area under a velocity time graph gives displacement.",
"Maths Tip: Remember exact trig values for 30, 45, and 60 degrees.",
"Maths Fun Fact: The sine graph has a period of 360 degrees or 2 pi radians.",
"Statistics Tip: The binomial distribution requires independent trials.",
"Statistics Fun Fact: The normal distribution is symmetric about the mean.",
"Statistics Tip: Standard deviation measures spread, not central tendency.",
"Statistics Fun Fact: Correlation does not imply causation.",
"Mechanics Tip: Equilibrium means resultant force equals zero.",
"Mechanics Fun Fact: Work done equals force times distance in the direction of motion.",
"Mechanics Tip: Moments are taken about a pivot point.",
"Mechanics Fun Fact: Kinetic energy equals one half m v squared.",
"Mechanics Tip: Friction always acts to oppose motion or attempted motion.",
"Mechanics Fun Fact: The centre of mass behaves as if all mass were concentrated there.",
"Decision 1 Tip: When performing the simplex algorithm, stop when there are no negative values left in the objective row for a maximisation problem.",
"Decision 1 Fun Fact: Degeneracy in simplex occurs when a basic variable becomes zero during a pivot.",
"Decision 1 Tip: In a transportation problem, start with the North West Corner method to find an initial feasible solution.",
"Decision 1 Fun Fact: Cycling in simplex is rare but can occur without anti cycling rules like Bland’s rule.",
"Decision 1 Tip: Total float equals latest start minus earliest start in project networks.",
"Decision 1 Fun Fact: A critical path is the longest path through a project network.",
"Decision 1 Tip: In Dijkstra’s algorithm, always select the smallest temporary label next.",
"Decision 1 Fun Fact: The assignment problem is a special case of the transportation problem.",
"Decision 1 Tip: In linear programming, slack variables convert inequalities into equations.",
"Decision 1 Fun Fact: Unbounded solutions occur when the feasible region is open in the direction of optimisation.",
"Further Mechanics 1 Tip: For inclined plane problems, resolve weight into components mg sin theta and mg cos theta.",
"Further Mechanics 1 Fun Fact: In elastic collisions, both momentum and kinetic energy are conserved.",
"Further Mechanics 1 Tip: Always check whether a collision is elastic or inelastic before applying energy equations.",
"Further Mechanics 1 Fun Fact: The coefficient of restitution lies between 0 and 1 for most exam problems.",
"Further Mechanics 1 Tip: Use conservation of momentum when no external forces act on the system.",
"Further Mechanics 1 Fun Fact: The impulse experienced by two colliding bodies is equal in magnitude and opposite in direction.",
"Further Mechanics 1 Tip: When finding work done, ensure displacement is in the direction of the force.",
"Further Mechanics 1 Fun Fact: The centripetal force is not a new force but the resultant towards the centre.",
"Core Pure 1 Tip: For series proof by induction, assume true for n equals k before proving for k plus 1.",
"Core Pure 1 Fun Fact: The argument of a complex number is measured from the positive real axis.",
"Core Pure 1 Tip: When multiplying complex numbers in polar form, multiply moduli and add arguments.",
"Core Pure 1 Fun Fact: The roots of unity lie equally spaced on the unit circle.",
"Core Pure 1 Tip: Use the formula for the sum of a geometric series when absolute value of r is less than 1.",
"Core Pure 1 Fun Fact: Eigenvalues satisfy the equation determinant of A minus lambda I equals zero.",
"Core Pure 1 Tip: When diagonalising a matrix, ensure you have enough independent eigenvectors.",
"Core Pure 1 Fun Fact: The trace of a matrix equals the sum of its eigenvalues.",
"Core Pure 2 Tip: For implicit differentiation, treat y as a function of x.",
"Core Pure 2 Fun Fact: The derivative of ln x is 1 over x.",
"Core Pure 2 Tip: When solving differential equations by separation, integrate both sides carefully.",
"Core Pure 2 Fun Fact: The vector cross product produces a vector perpendicular to both originals.",
"Core Pure 2 Tip: The magnitude of the cross product equals the area of the parallelogram formed by two vectors.",
"Core Pure 2 Fun Fact: Taylor series approximations improve as more terms are included.",
"Core Pure 2 Tip: Check convergence when working with infinite series.",
"Core Pure 2 Fun Fact: The binomial series expansion works for non integer powers when absolute value of x is less than 1.",
"Maths Tip: The factor theorem states that if f a equals zero then x minus a is a factor.",
"Maths Fun Fact: The remainder theorem allows quick evaluation of polynomial remainders.",
"Maths Tip: When solving trig equations, always give answers in the required interval.",
"Maths Fun Fact: The cosine rule works for any triangle, not just right angled ones.",
"Maths Tip: Use radians in calculus questions involving trigonometric functions.",
"Maths Fun Fact: The gradient of a perpendicular line is the negative reciprocal.",
"Statistics Tip: For large n, a binomial distribution can be approximated by a normal distribution.",
"Statistics Fun Fact: The mean of a Poisson distribution equals its variance.",
"Statistics Tip: Always apply continuity correction when approximating discrete distributions with normal.",
"Statistics Fun Fact: In hypothesis testing, a small p value suggests evidence against the null hypothesis.",
"Mechanics Tip: When using SUVAT, clearly define a positive direction first.",
"Mechanics Fun Fact: The area under a force extension graph gives elastic potential energy.",
"Mechanics Tip: In connected particle problems, write separate equations for each particle.",
"Mechanics Fun Fact: A particle moving in a circle at constant speed is still accelerating.",
"Mechanics Tip: Check whether friction is limiting before setting F equals mu R.",
"Decision 1 Tip: Always check for redundant constraints before starting the simplex method to simplify calculations.",
"Decision 1 Fun Fact: A feasible region can be empty if constraints contradict each other.",
"Decision 1 Tip: In the two phase simplex method, Phase 1 removes artificial variables before optimising the real objective.",
"Decision 1 Fun Fact: The shortest path in a tree is unique because trees contain no cycles.",
"Decision 1 Tip: When improving a transportation solution, use the stepping stone or MODI method.",
"Decision 1 Fun Fact: A spanning tree connects all vertices without forming any loops.",
"Decision 1 Tip: In network flow problems, the total flow into a node equals the total flow out, except at source and sink.",
"Decision 1 Fun Fact: The maximum flow minimum cut theorem links flows and cuts in networks.",
"Decision 1 Tip: If no valid pivot row exists in simplex, the solution is unbounded.",
"Decision 1 Fun Fact: Integer programming requires additional methods beyond standard simplex.",
"Further Mechanics 1 Tip: When modelling with connected particles, check whether the string becomes slack.",
"Further Mechanics 1 Fun Fact: In perfectly inelastic collisions, objects move together after impact.",
"Further Mechanics 1 Tip: Use energy conservation when forces are conservative and no energy is lost.",
"Further Mechanics 1 Fun Fact: The work energy principle links net work done to change in kinetic energy.",
"Further Mechanics 1 Tip: For variable acceleration given as a function of time, integrate to find velocity.",
"Further Mechanics 1 Fun Fact: Simple harmonic motion acceleration is proportional to displacement from equilibrium.",
"Further Mechanics 1 Tip: When dealing with banks in circular motion, resolve forces carefully towards the centre.",
"Further Mechanics 1 Fun Fact: Terminal velocity occurs when resultant force equals zero.",
"Core Pure 1 Tip: When solving recurrence relations, look for characteristic equations.",
"Core Pure 1 Fun Fact: The sum of the first n natural numbers equals n times n plus 1 divided by 2.",
"Core Pure 1 Tip: Use De Moivre’s theorem for powers and roots of complex numbers.",
"Core Pure 1 Fun Fact: The cube roots of unity sum to zero.",
"Core Pure 1 Tip: Check matrix multiplication dimensions before calculating.",
"Core Pure 1 Fun Fact: An orthogonal matrix has its inverse equal to its transpose.",
"Core Pure 1 Tip: When sketching Argand diagrams, label real and imaginary axes clearly.",
"Core Pure 1 Fun Fact: The modulus argument form simplifies multiplication of complex numbers.",
"Core Pure 2 Tip: For parametric equations, differentiate y and x separately with respect to the parameter.",
"Core Pure 2 Fun Fact: The derivative of tan x is sec squared x.",
"Core Pure 2 Tip: When integrating rational functions, consider partial fractions.",
"Core Pure 2 Fun Fact: The divergence of a constant vector field is zero.",
"Core Pure 2 Tip: In differential equations, include a constant of integration.",
"Core Pure 2 Fun Fact: The Laplace expansion can be used to find determinants of larger matrices.",
"Core Pure 2 Tip: When finding stationary points, set the derivative equal to zero.",
"Core Pure 2 Fun Fact: A zero dot product implies vectors are perpendicular.",
"Maths Tip: Always factorise fully before solving algebraic equations.",
"Maths Fun Fact: The area of a triangle can be found using one half ab sin C.",
"Maths Tip: In coordinate geometry, use the midpoint formula for segment centres.",
"Maths Fun Fact: The exponential function never crosses the x axis.",
"Maths Tip: Use exact values unless the question requests decimals.",
"Maths Fun Fact: The sine rule can lead to the ambiguous case in non right angled triangles.",
"Statistics Tip: Define the random variable clearly before calculating probabilities.",
"Statistics Fun Fact: The expected value represents the long run average outcome.",
"Statistics Tip: Always check conditions before using a normal approximation.",
"Statistics Fun Fact: The variance is the square of the standard deviation.",
"Mechanics Tip: When resolving forces, keep consistent sign conventions.",
"Mechanics Fun Fact: The gradient of a displacement time graph gives velocity.",
"Mechanics Tip: Use conservation of energy when friction is absent.",
"Mechanics Fun Fact: Potential energy decreases as kinetic energy increases in free fall.",
"Mechanics Tip: In moments problems, take moments about the pivot to eliminate unknown reactions.",
"Decision 1 Tip: When using the simplex method, rewrite the objective function in the form P minus the expression equals zero before forming the tableau.",
"Decision 1 Fun Fact: A linear programming problem can have multiple optimal solutions if the objective function is parallel to a constraint boundary.",
"Decision 1 Tip: Always state whether you are maximising or minimising before starting your method.",
"Decision 1 Fun Fact: In a project network, dummy activities are used to show dependency without adding time.",
"Decision 1 Tip: When finding earliest event times, work forwards through the network.",
"Decision 1 Fun Fact: Latest event times are found by working backwards from the final node.",
"Decision 1 Tip: Check that all decision variables are non negative in standard form.",
"Decision 1 Fun Fact: A feasible region formed by linear inequalities is always a convex set.",
"Decision 1 Tip: In minimisation problems, convert to maximisation if your method requires it.",
"Decision 1 Fun Fact: The graphical method only works easily for two variable linear programming problems.",
"Further Mechanics 1 Tip: When modelling with pulleys, assume they are smooth unless told otherwise.",
"Further Mechanics 1 Fun Fact: In uniform circular motion, velocity is tangent to the circle at every point.",
"Further Mechanics 1 Tip: Use conservation of momentum in explosion type problems.",
"Further Mechanics 1 Fun Fact: The coefficient of friction is dimensionless.",
"Further Mechanics 1 Tip: When solving SHM problems, use a equals minus omega squared x.",
"Further Mechanics 1 Fun Fact: The period of simple harmonic motion equals 2 pi divided by omega.",
"Further Mechanics 1 Tip: Clearly label all forces before forming equations of motion.",
"Further Mechanics 1 Fun Fact: Mechanical energy is conserved when only conservative forces act.",
"Core Pure 1 Tip: When expanding binomials, remember to increase powers of x while decreasing powers of the constant.",
"Core Pure 1 Fun Fact: Pascal’s triangle patterns appear in binomial coefficients.",
"Core Pure 1 Tip: When solving simultaneous equations with matrices, you can use the inverse matrix method.",
"Core Pure 1 Fun Fact: The identity matrix leaves a vector unchanged when multiplied.",
"Core Pure 1 Tip: For geometric series, ensure the common ratio is constant.",
"Core Pure 1 Fun Fact: If the absolute value of r is less than one, an infinite geometric series converges.",
"Core Pure 1 Tip: Always write complex numbers in a plus bi form unless asked otherwise.",
"Core Pure 1 Fun Fact: Multiplying by the conjugate removes imaginary parts in denominators.",
"Core Pure 2 Tip: When differentiating inverse trig functions, remember their standard derivatives.",
"Core Pure 2 Fun Fact: The derivative of arcsin x is 1 over square root of 1 minus x squared.",
"Core Pure 2 Tip: Use substitution when an integral contains a function and its derivative.",
"Core Pure 2 Fun Fact: The binomial series can approximate roots such as square root of 1 plus x.",
"Core Pure 2 Tip: When finding vector equations of lines, use position vector plus parameter times direction vector.",
"Core Pure 2 Fun Fact: Two lines are parallel if their direction vectors are scalar multiples.",
"Core Pure 2 Tip: Check second derivative to classify stationary points.",
"Core Pure 2 Fun Fact: A positive second derivative indicates a local minimum.",
"Maths Tip: Use the chain rule when differentiating composite functions.",
"Maths Fun Fact: The derivative represents instantaneous rate of change.",
"Maths Tip: When solving logarithmic equations, ensure arguments remain positive.",
"Maths Fun Fact: e is an irrational number approximately equal to 2.718.",
"Maths Tip: Sketch graphs to understand transformations clearly.",
"Maths Fun Fact: The tangent to a curve touches it at exactly one point locally.",
"Statistics Tip: Clearly state null and alternative hypotheses in context.",
"Statistics Fun Fact: A Type I error occurs when a true null hypothesis is rejected.",
"Statistics Tip: Use tables carefully and interpolate if required.",
"Statistics Fun Fact: The Poisson distribution models rare events in fixed intervals.",
"Mechanics Tip: Define positive direction before applying Newton’s Second Law.",
"Mechanics Fun Fact: Acceleration is the rate of change of velocity.",
"Mechanics Tip: In equilibrium problems, set both sum of forces and sum of moments equal to zero.",
"Mechanics Fun Fact: A resultant force of zero means constant velocity or rest.",
"Mechanics Tip: Always include units in final answers."
    ];
    const randomTip = tips[Math.floor(Math.random() * tips.length)];
    const tipElement = document.querySelector(".math-tip p");
    if (tipElement) tipElement.textContent = randomTip;
    const closeBtn = document.querySelector(".close-tip");
    const mathTip = document.querySelector(".math-tip");
    if (closeBtn && mathTip) {
        closeBtn.addEventListener("click", () => {
            mathTip.classList.add("hidden");
            setTimeout(() => mathTip.style.display = "none", 400);
        });
    }
    if (localStorage.getItem('theme') == 'dark') {
        body.classList.add('dark-mode');
        toggleButton.textContent = '☀️';
    }

    toggleButton.addEventListener('click', () => {
        body.classList.toggle('dark-mode');
        if (body.classList.contains('dark-mode')) {
            toggleButton.textContent = '☀️';
            localStorage.setItem('theme', 'dark');
        } else {
            toggleButton.textContent = '🌙';
            localStorage.setItem('theme', 'light');
        }
    });
    body.classList.add('fade-in');
    const links = document.querySelectorAll('a.NavItem, a.home');
    links.forEach(link => {
        link.addEventListener('click', (e) => {
            e.preventDefault();
            const href = link.getAttribute('href');
            body.classList.remove('fade-in');
            body.classList.add('fade-out');
            setTimeout(() => window.location.href = href, 300);
        });
    });
});
